remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

title: Koi Bräu Homebrewery by Philip Voss
description: This Page is displaying the different beers brewed by the Koi Bräu Homebrewery by Philip Voss. The beers are not for sale.
